name:                cairo-image
version:             0.1.0.5
github:              "YoshikuniJujo/cairo-image"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo@gmail.com"
copyright:           "2021 Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Image for Cairo
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/cairo-image#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell >= 2.18.0 && < 2.24
- primitive >= 0.8.0 && < 0.10
- c-enum >= 0.1.1 && < 0.2

library:
  source-dirs: src
  exposed-modules:
  - Data.CairoImage
  - Data.CairoImage.Internal
  - System.TargetEndian
  pkg-config-dependencies: cairo

tests:
  cairo-image-test:
    main:                spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cairo-image
  test-endian:
    main:                endian.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cairo-image
