name:                cairo-image
version:             0.1.0.0
github:              "githubuser/cairo-image"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cairo-image#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- primitive

library:
  source-dirs: src
  exposed-modules:
  - Data.CairoImage
  - Data.CairoImage.Internal
  pkg-config-dependencies: cairo

tests:
  cairo-image-test:
    main:                spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cairo-image
  test-endian:
    main:                endian.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cairo-image
